
-- SQL Assignment Solutions for Maven Movies Database

-- BASIC SQL & FILTERING

-- 1. Identify the primary keys and foreign keys in maven movies db
-- Answer: See table definitions (example below for customer)
-- Primary Key: customer_id
-- Foreign Keys: address_id -> address(address_id), store_id -> store(store_id)

-- 2. List all details of actors
SELECT * FROM actor;

-- 3. List all customer information from DB
SELECT * FROM customer;

-- 4. List different countries
SELECT DISTINCT country FROM country;

-- 5. Display all active customers
SELECT * FROM customer WHERE active = 1;

-- 6. List of all rental IDs for customer with ID 1
SELECT rental_id FROM rental WHERE customer_id = 1;

-- 7. Display all the films whose rental duration is greater than 5
SELECT * FROM film WHERE rental_duration > 5;

-- 8. List the total number of films whose replacement cost is greater than $15 and less than $20
SELECT COUNT(*) FROM film WHERE replacement_cost BETWEEN 15 AND 20;

-- 9. Display the count of unique first names of actors
SELECT COUNT(DISTINCT first_name) AS unique_first_names FROM actor;

-- 10. Display the first 10 records from the customer table
SELECT * FROM customer LIMIT 10;

-- 11. Display the first 3 records from the customer table whose first name starts with ‘b’
SELECT * FROM customer WHERE first_name ILIKE 'b%' LIMIT 3;

-- 12. Display the names of the first 5 movies which are rated as ‘G’
SELECT title FROM film WHERE rating = 'G' LIMIT 5;

-- 13. Find all customers whose first name starts with "a"
SELECT * FROM customer WHERE first_name ILIKE 'a%';

-- 14. Find all customers whose first name ends with "a"
SELECT * FROM customer WHERE first_name ILIKE '%a';

-- 15. Display the list of first 4 cities which start and end with ‘a’
SELECT * FROM city WHERE city ILIKE 'a%a' LIMIT 4;

-- 16. Find all customers whose first name have "NI" in any position
SELECT * FROM customer WHERE first_name ILIKE '%NI%';

-- 17. Find all customers whose first name have "r" in the second position
SELECT * FROM customer WHERE first_name ILIKE '_r%';

-- 18. Find all customers whose first name starts with "a" and are at least 5 characters in length
SELECT * FROM customer WHERE first_name ILIKE 'a%' AND LENGTH(first_name) >= 5;

-- 19. Find all customers whose first name starts with "a" and ends with "o"
SELECT * FROM customer WHERE first_name ILIKE 'a%o';

-- 20. Get the films with pg and pg-13 rating using IN operator
SELECT * FROM film WHERE rating IN ('PG', 'PG-13');

-- 21. Get the films with length between 50 to 100 using BETWEEN operator
SELECT * FROM film WHERE length BETWEEN 50 AND 100;

-- 22. Get the top 50 actors using LIMIT operator
SELECT * FROM actor LIMIT 50;

-- 23. Get the distinct film ids from inventory table
SELECT DISTINCT film_id FROM inventory;

-- FUNCTIONS

-- 1. Retrieve the total number of rentals made in the Sakila database
SELECT COUNT(*) AS total_rentals FROM rental;

-- 2. Find the average rental duration (in days) of movies
SELECT AVG(rental_duration) AS avg_rental_duration FROM film;

-- 3. Display the first name and last name of customers in uppercase
SELECT UPPER(first_name) AS first_name_upper, UPPER(last_name) AS last_name_upper FROM customer;

-- 4. Extract the month from the rental date and display it alongside the rental ID
SELECT rental_id, EXTRACT(MONTH FROM rental_date) AS rental_month FROM rental;

-- GROUP BY

-- 5. Retrieve the count of rentals for each customer
SELECT customer_id, COUNT(*) AS rental_count FROM rental GROUP BY customer_id;

-- 6. Find the total revenue generated by each store
SELECT store_id, SUM(amount) AS total_revenue FROM payment JOIN staff USING (staff_id) GROUP BY store_id;

-- 7. Determine the total number of rentals for each category of movies
SELECT c.name AS category, COUNT(r.rental_id) AS rental_count
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name;

-- 8. Find the average rental rate of movies in each language
SELECT l.name AS language, AVG(f.rental_rate) AS avg_rental_rate
FROM film f
JOIN language l ON f.language_id = l.language_id
GROUP BY l.name;

-- JOINS

-- 9. Display the title of the movie, customer's first and last name who rented it
SELECT f.title, c.first_name, c.last_name
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
JOIN customer c ON r.customer_id = c.customer_id;

-- 10. Retrieve the names of all actors who have appeared in the film "Gone with the Wind"
SELECT a.first_name, a.last_name
FROM film f
JOIN film_actor fa ON f.film_id = fa.film_id
JOIN actor a ON fa.actor_id = a.actor_id
WHERE f.title = 'Gone with the Wind';

-- 11. Retrieve the customer names along with the total amount they've spent on rentals
SELECT c.first_name, c.last_name, SUM(p.amount) AS total_spent
FROM customer c
JOIN payment p ON c.customer_id = p.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name;

-- 12. List the titles of movies rented by each customer in the city 'London'
SELECT c.first_name, c.last_name, f.title
FROM customer c
JOIN address a ON c.address_id = a.address_id
JOIN city ct ON a.city_id = ct.city_id
JOIN rental r ON c.customer_id = r.customer_id
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
WHERE ct.city = 'London';

-- ADVANCED JOINS & WINDOW FUNCTIONS

-- 13. Top 5 rented movies with rental count
SELECT f.title, COUNT(r.rental_id) AS rental_count
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 5;

-- 14. Customers who have rented from both stores (store ID 1 and 2)
SELECT customer_id
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
GROUP BY customer_id
HAVING COUNT(DISTINCT i.store_id) = 2;

-- 1. Rank customers based on total amount spent
SELECT customer_id, first_name, last_name, SUM(amount) AS total_spent,
       RANK() OVER (ORDER BY SUM(amount) DESC) AS rank
FROM customer
JOIN payment USING (customer_id)
GROUP BY customer_id, first_name, last_name;

-- 2. Cumulative revenue generated by each film over time
SELECT f.title, p.payment_date, SUM(p.amount) OVER (PARTITION BY f.film_id ORDER BY p.payment_date) AS cumulative_revenue
FROM payment p
JOIN rental r ON p.rental_id = r.rental_id
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id;

-- 3. Average rental duration per film, grouped by length
SELECT title, length,
       AVG(rental_duration) OVER (PARTITION BY length) AS avg_duration_for_length
FROM film;

-- 4. Top 3 films in each category based on rental counts
WITH film_rentals AS (
  SELECT c.name AS category, f.title, COUNT(r.rental_id) AS rental_count,
         RANK() OVER (PARTITION BY c.name ORDER BY COUNT(r.rental_id) DESC) AS rank
  FROM rental r
  JOIN inventory i ON r.inventory_id = i.inventory_id
  JOIN film f ON i.film_id = f.film_id
  JOIN film_category fc ON f.film_id = fc.film_id
  JOIN category c ON fc.category_id = c.category_id
  GROUP BY c.name, f.title
)
SELECT * FROM film_rentals WHERE rank <= 3;

-- 5. Difference in rental count between customer and overall average
WITH customer_rentals AS (
  SELECT customer_id, COUNT(*) AS rental_count
  FROM rental
  GROUP BY customer_id
),
avg_rentals AS (
  SELECT AVG(rental_count) AS avg_rental FROM customer_rentals
)
SELECT cr.customer_id, cr.rental_count, (cr.rental_count - ar.avg_rental) AS difference
FROM customer_rentals cr, avg_rentals ar;

-- 6. Monthly revenue trend
SELECT DATE_TRUNC('month', payment_date) AS month, SUM(amount) AS monthly_revenue
FROM payment
GROUP BY month
ORDER BY month;

-- 7. Customers in top 20% of spending
WITH spending AS (
  SELECT customer_id, SUM(amount) AS total_spent
  FROM payment
  GROUP BY customer_id
),
ranked AS (
  SELECT customer_id, total_spent,
         PERCENT_RANK() OVER (ORDER BY total_spent DESC) AS percent_rank
  FROM spending
)
SELECT * FROM ranked WHERE percent_rank <= 0.2;

-- 8. Running total of rentals per category
WITH rentals_per_category AS (
  SELECT c.name AS category, COUNT(r.rental_id) AS rental_count
  FROM rental r
  JOIN inventory i ON r.inventory_id = i.inventory_id
  JOIN film f ON i.film_id = f.film_id
  JOIN film_category fc ON f.film_id = fc.film_id
  JOIN category c ON fc.category_id = c.category_id
  GROUP BY c.name
)
SELECT category, rental_count,
       SUM(rental_count) OVER (ORDER BY rental_count DESC) AS running_total
FROM rentals_per_category;

-- 9. Films rented less than average in their category
WITH film_rentals AS (
  SELECT f.film_id, f.title, c.name AS category, COUNT(r.rental_id) AS rental_count
  FROM rental r
  JOIN inventory i ON r.inventory_id = i.inventory_id
  JOIN film f ON i.film_id = f.film_id
  JOIN film_category fc ON f.film_id = fc.film_id
  JOIN category c ON fc.category_id = c.category_id
  GROUP BY f.film_id, f.title, c.name
),
category_avg AS (
  SELECT category, AVG(rental_count) AS avg_rentals
  FROM film_rentals
  GROUP BY category
)
SELECT fr.*
FROM film_rentals fr
JOIN category_avg ca ON fr.category = ca.category
WHERE fr.rental_count < ca.avg_rentals;

-- 10. Top 5 months with highest revenue
SELECT DATE_TRUNC('month', payment_date) AS month, SUM(amount) AS revenue
FROM payment
GROUP BY month
ORDER BY revenue DESC
LIMIT 5;

-- CTEs

-- CTE: Distinct actor names and number of films they acted in
WITH actor_films AS (
  SELECT actor_id, COUNT(film_id) AS film_count
  FROM film_actor
  GROUP BY actor_id
)
SELECT a.first_name, a.last_name, af.film_count
FROM actor a
JOIN actor_films af ON a.actor_id = af.actor_id;

-- CTE: Film title, language, rental rate
WITH film_lang AS (
  SELECT f.title, l.name AS language, f.rental_rate
  FROM film f
  JOIN language l ON f.language_id = l.language_id
)
SELECT * FROM film_lang;

-- CTE: Total revenue per customer
WITH customer_revenue AS (
  SELECT customer_id, SUM(amount) AS total_spent
  FROM payment
  GROUP BY customer_id
)
SELECT c.first_name, c.last_name, cr.total_spent
FROM customer c
JOIN customer_revenue cr ON c.customer_id = cr.customer_id;

-- CTE: Rank films by rental duration
WITH ranked_films AS (
  SELECT title, rental_duration,
         RANK() OVER (ORDER BY rental_duration DESC) AS duration_rank
  FROM film
)
SELECT * FROM ranked_films;

-- CTE: Customers with >2 rentals and their details
WITH frequent_customers AS (
  SELECT customer_id
  FROM rental
  GROUP BY customer_id
  HAVING COUNT(*) > 2
)
SELECT c.*
FROM customer c
JOIN frequent_customers fc ON c.customer_id = fc.customer_id;

-- CTE: Total number of rentals made each month
WITH monthly_rentals AS (
  SELECT DATE_TRUNC('month', rental_date) AS month, COUNT(*) AS total_rentals
  FROM rental
  GROUP BY month
)
SELECT * FROM monthly_rentals ORDER BY month;

-- CTE: Actor pairs who acted in the same film
WITH actor_pairs AS (
  SELECT fa1.actor_id AS actor1, fa2.actor_id AS actor2, fa1.film_id
  FROM film_actor fa1
  JOIN film_actor fa2 ON fa1.film_id = fa2.film_id
  WHERE fa1.actor_id < fa2.actor_id
)
SELECT ap.actor1, a1.first_name || ' ' || a1.last_name AS actor1_name,
       ap.actor2, a2.first_name || ' ' || a2.last_name AS actor2_name,
       ap.film_id
FROM actor_pairs ap
JOIN actor a1 ON ap.actor1 = a1.actor_id
JOIN actor a2 ON ap.actor2 = a2.actor_id;

-- Recursive CTE: Find employees reporting to a manager
WITH RECURSIVE subordinates AS (
  SELECT staff_id, first_name, last_name, reports_to
  FROM staff
  WHERE reports_to = 1  -- Replace with manager ID

  UNION ALL

  SELECT s.staff_id, s.first_name, s.last_name, s.reports_to
  FROM staff s
  INNER JOIN subordinates sub ON s.reports_to = sub.staff_id
)
SELECT * FROM subordinates;

-- NORMALIZATION (Theoretical)
-- 1NF: Ensure atomic values
-- 2NF: Remove partial dependencies
-- 3NF: Remove transitive dependencies
